[package]
name = "fusion-imu-sys"
version = "0.1.2"
edition = "2024"
description = "Generated bindings for the Fusion AHRS C library"
categories = ["external-ffi-bindings", "algorithms"]
keywords = ["no-std", "ahrs", "imu"]
license = "MIT"
repository = "https://github.com/avsaase/fusion-imu"

links = "fusion"

[dependencies]


[build-dependencies]
bindgen = { version = "0.72.1"}
cc = "1.2.61"
